### ISSUE TITLE
Installing according to README.md fails

### ISSUE THREAD

**Issue by Numero7** [MieuxVoter/mvapi#44]
### Issue and Steps to Reproduce
I followed README.md for installing on a Ubuntu server 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Creating and starting the docker image went fine

```
user@server:~/Code/mvapi$ sudo docker container ls
[sudo] password for gimbert: 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
09f788463084        postgres            "docker-entrypoint.s…"   30 minutes ago      Up 30 minutes       5432/tcp            mvapi_db_1

```
But scripts for migrating databses, creating the super user and launching tests all fail with error

Error response from daemon: Container 32a39bd156070ff66f0faef01aa6e3480c92ebb651386a58cfc61b6c49b283c1 is not running

**Comment by guhur** [comment]
You are supposed to get another container running, called `mvapi_web_1`.
Something bad happens during its launch. You'll know more about with `docker-compose logs`

**Comment by Numero7** [comment]
Thanks for the feedback.
After installing
`python -m pip install Django`
and adding a secret key in .env I could execute smoothly
`sudo docker/migrate.sh`
```
sudo docker exec -it mvapi_web_1 python ./manage.py createsuperuser
```
but on the other hand
`sudo docker/test.sh`
failed with error
'''
user@server:~/Code/mvapi$ sudo docker/test.sh
System check identified no issues (0 silenced).
E
======================================================================
ERROR: election.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: election.tests
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/code/election/tests.py", line 8, in <module>
    from election.models import MAX_NUM_GRADES, Election, Token, Vote
ImportError: cannot import name 'MAX_NUM_GRADES' from 'election.models' (/code/election/models.py)


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
'''
